### ISSUE TITLE
'.Random.seed' is not an integer vector but of type 'NULL', so ignored

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#44]
The above message started to appear in RC10.  In RC9 this does not occur.

**Comment by steve-s** [comment]
Hello Rodrigo, 

thanks for the report. We noticed this issue appearing with `ggplot2` and `dplyr` (and it actually comes from `withr::with_preserve_seed`). This should be fixed by 2a013333d46f349e878da64d26499eb40167a152. You can test the development version of FastR with https://github.com/nuest/fastr-docker. Please reopen if your issue is something else.
