### ISSUE TITLE
Avoid unhandled exceptions in `ggsave` and display an error instead

### ISSUE THREAD

**Issue by fniephaus** [oracle/fastr#76]
Repro:
```R
GraalVM MultiLanguage Shell 1.0.0-rc16
Copyright (c) 2013-2019, Oracle and/or its affiliates
  R version 3.5.1
Setting LC_COLLATE failed, using default
Setting LC_MONETARY failed, using default
Setting LC_TIME failed, using default
Setting LC_MESSAGES failed, using default
R> library(ggplot2)
R> ggplot(mtcars, aes(mpg, wt)) + geom_point()
R> ggsave("foo.svg", width = 2, height = 2, units = "cm")
```

Error log: [fastr_errors_pid32647.log](https://github.com/oracle/fastr/files/3170568/fastr_errors_pid32647.log)

**Comment by steve-s** [comment]
Hello Fabio,

thank you for the report. `ggsave` internally uses `svglite` for the SVG format and FastR does not support `svglite` or any other native GNU-R graphics devices. This is a limitation that we would like to remove at some point. Nonetheless, we should produce an error message rather than an unhandled exception.

`ggsave` allows you to specify the device by means of an R function, this works fine for me:

```
ggsave("foo.svg", dev=function(filename,width,height,...) svg(filename,7,7,...), width = 2, height = 2, units = "cm")
```

On the first quick look, I didn't find documentation on how the `width`, `height` should be interpreted, so I just hard-coded the values, which can/should be improved.

**Comment by fniephaus** [comment]
Hey @steve-s,
Thanks for info! In the meantime, we found `svg.off()` in the [reference manual](https://www.graalvm.org/docs/reference-manual/languages/r/) which seems to work fine for our use case. But I agree, a better error message would be good.

**Comment by steve-s** [comment]
Should be fixed now.

**Comment by fniephaus** [comment]
Thanks, @steve-s!
