### ISSUE TITLE
Bookdown not working

### ISSUE THREAD

**Issue by rbotafogo** [oracle/fastr#77]
I've installed package 'bookdown' and created a directory with the "Minimal Book Example".  Then I try from the R console: bookdown::render_book("index.Rmd", "bookdown::pdf_book") and get
the following error:

Error in check_special_chars(files) : object 'i' not found

I've done it with both 19.0 and RC 16 with the same result.

**Comment by steve-s** [comment]
Hello Rodrigo, 

thank you for the report. The issue reported here is fixed. However, the bookdown example fails because FastR does not support the PDF device at the moment. It is planned, but we do not have any concrete time frame for it yet. Maybe you can try configuring bookdown so that it uses another graphical device like `svg`, `jpeg` or `png`.
